// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/petro/GoProjects/graduation/internal/storage/storage.go

// Package storage is a generated GoMock package.
package mock

import (
	context "context"
	entity "graduation/internal/entity"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// AddEventUser mocks base method.
func (m *MockStorage) AddEventUser(ctx context.Context, eventID, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddEventUser", ctx, eventID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddEventUser indicates an expected call of AddEventUser.
func (mr *MockStorageMockRecorder) AddEventUser(ctx, eventID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddEventUser", reflect.TypeOf((*MockStorage)(nil).AddEventUser), ctx, eventID, userID)
}

// CloseEvent mocks base method.
func (m *MockStorage) CloseEvent(ctx context.Context, userID, eventID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseEvent", ctx, userID, eventID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseEvent indicates an expected call of CloseEvent.
func (mr *MockStorageMockRecorder) CloseEvent(ctx, userID, eventID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseEvent", reflect.TypeOf((*MockStorage)(nil).CloseEvent), ctx, userID, eventID)
}

// CreateEvent mocks base method.
func (m *MockStorage) CreateEvent(ctx context.Context, e *entity.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEvent", ctx, e)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateEvent indicates an expected call of CreateEvent.
func (mr *MockStorageMockRecorder) CreateEvent(ctx, e interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEvent", reflect.TypeOf((*MockStorage)(nil).CreateEvent), ctx, e)
}

// DellEvent mocks base method.
func (m *MockStorage) DellEvent(ctx context.Context, userID, eventID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DellEvent", ctx, userID, eventID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DellEvent indicates an expected call of DellEvent.
func (mr *MockStorageMockRecorder) DellEvent(ctx, userID, eventID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DellEvent", reflect.TypeOf((*MockStorage)(nil).DellEvent), ctx, userID, eventID)
}

// DellEventUser mocks base method.
func (m *MockStorage) DellEventUser(ctx context.Context, eventID, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DellEventUser", ctx, eventID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DellEventUser indicates an expected call of DellEventUser.
func (mr *MockStorageMockRecorder) DellEventUser(ctx, eventID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DellEventUser", reflect.TypeOf((*MockStorage)(nil).DellEventUser), ctx, eventID, userID)
}

// GetEvent mocks base method.
func (m *MockStorage) GetEvent(ctx context.Context, eventID int) (*entity.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEvent", ctx, eventID)
	ret0, _ := ret[0].(*entity.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEvent indicates an expected call of GetEvent.
func (mr *MockStorageMockRecorder) GetEvent(ctx, eventID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEvent", reflect.TypeOf((*MockStorage)(nil).GetEvent), ctx, eventID)
}

// GetEvents mocks base method.
func (m *MockStorage) GetEvents(ctx context.Context, from, to time.Time, limit, page int) ([]entity.Event, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEvents", ctx, from, to, limit, page)
	ret0, _ := ret[0].([]entity.Event)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetEvents indicates an expected call of GetEvents.
func (mr *MockStorageMockRecorder) GetEvents(ctx, from, to, limit, page interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEvents", reflect.TypeOf((*MockStorage)(nil).GetEvents), ctx, from, to, limit, page)
}

// GetImage mocks base method.
func (m *MockStorage) GetImage(ctx context.Context, filename string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetImage", ctx, filename)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetImage indicates an expected call of GetImage.
func (mr *MockStorageMockRecorder) GetImage(ctx, filename interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImage", reflect.TypeOf((*MockStorage)(nil).GetImage), ctx, filename)
}

// GetUser mocks base method.
func (m *MockStorage) GetUser(ctx context.Context, login, password string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, login, password)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockStorageMockRecorder) GetUser(ctx, login, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockStorage)(nil).GetUser), ctx, login, password)
}

// GetUserEvents mocks base method.
func (m *MockStorage) GetUserEvents(ctx context.Context, userID int) ([]entity.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserEvents", ctx, userID)
	ret0, _ := ret[0].([]entity.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserEvents indicates an expected call of GetUserEvents.
func (mr *MockStorageMockRecorder) GetUserEvents(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserEvents", reflect.TypeOf((*MockStorage)(nil).GetUserEvents), ctx, userID)
}

// SendMessage mocks base method.
func (m *MockStorage) SendMessage(ctx context.Context, date time.Time, send func(string, string, []string) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", ctx, date, send)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockStorageMockRecorder) SendMessage(ctx, date, send interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockStorage)(nil).SendMessage), ctx, date, send)
}

// SetUser mocks base method.
func (m *MockStorage) SetUser(ctx context.Context, login, password, mail string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUser", ctx, login, password, mail)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetUser indicates an expected call of SetUser.
func (mr *MockStorageMockRecorder) SetUser(ctx, login, password, mail interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUser", reflect.TypeOf((*MockStorage)(nil).SetUser), ctx, login, password, mail)
}
